### PR TITLE
Moving towards more unit tests

### PR DESCRIPTION
**Pull request by JoachimL**
First attempt at unit testing the check out process - I chose to create tests for the dibs controller. 
For a variety of reasons, quite a lot of refactoring was needed. It was impossible to mock out purchaseorder, so I had to extend the order service to add mapping to a new layer of model objects. This could and should be done by something like AutoMapper in the future.
I removed a lot of protected methods from the base checkout controller, instead moving the methods into separate interfaces, favoring composition over inheritance.
There is a lot of dependency injection "cheating" (getting the dependency when needed instead of at runtime, sneaking in mutability and making dependencies much harder to find). To cater for the unit testing these had to be removed and passed as parameters or injected to the constructor. This, in turn, exposed classes with too many dependencies/ a high level of coupling (GenericPaymentController).
I removed IMarket from DTO (OrderViewModel) to be able to create the model.
Xhtmlstring is a bother! The properties of its type need to be virtual to be able to test anything related to it at all. The IFragmentParser stuff really should be handled some other way.

All in all, few tests are added at this point, but the solution is at a stage where it's beginning to be testable. As usual, when writing the tests, interfaces pop up all over the place, exposing both hidden and blatant coupling. IMO the changes are needed, for the the solution to be maintainable, but someone should really have a good look at this before merging. There's no reason to believe I haven't introduced any hidden (or blatant) bugs.

### CODE REVIEW

**Comment by evest** [comment]
Nice one. Fixing the DI cheats is high pri too. Haven't gotten around to test and merge this yet. Will give it a go towards the end of the week. Since it changes a lot, a thorough test is needed.

**Comment by evest** [comment]
I've merged the code and started testing. Quick check - the container registrations are all singletons. I haven't looked into them too much, and they probably can be, but wanted to check if this was on purpose.

**Comment by evest** [comment]
I painted myself into a corner, and had to merge manually, but all changes should be part of the commit. Thanks a lot for this one. Email failed during order creation, as the order model was not mapped, so I added some null checks for To address. I should have created tests for that too, but did not have time to finish that (need to invest time looking at your tests first.) At least this is now part of the master.

**Comment by evest** [comment]
Part of c5dcaa71384ea18374aeeecd80d9d17210afece3 so closing this.

**Comment by JoachimL** [comment]
Hello! Sorry for the late reply, was away over the weekend.

Yes, the singletons are done on purpose. In my experience, writing immutable singletons is the easiest way to reduce bugs, so I usually stick to that pattern. Thanks for the merge job!

**Pull request closed without merging**
